version: "3.8"

services:
  mongo:
    image: mongo
    container_name: argentbank-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped # Ensures MongoDB stays up

  backend:
    build: ./ArgentBank-back
    container_name: argentbank-backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/argentBank
    volumes:
      - ./ArgentBank-back:/app
      - /app/node_modules/ # Prevents overwriting node_modules
    command: ["npm", "run", "dev:server"]
    restart: unless-stopped # Ensures backend stays up

  frontend:
    build: ./ArgentBank-front
    container_name: argentbank-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./ArgentBank-front:/app
      - /app/node_modules/ # Prevents overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: ["yarn", "dev"]
    restart: unless-stopped # Ensures frontend stays up

volumes:
  mongo_data:
