swagger: "2.0"

info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"

host: localhost:3001

basePath: /api/v1

schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get user accounts
      description: Retrieve the list of accounts belonging to the authenticated user.
      produces:
        - application/json
      responses:
        "200":
          description: List of user accounts
          schema:
            type: array
            items:
              $ref: "#/definitions/Account"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  /accounts/{account_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get account details
      description: Retrieve detailed information about a specific account.
      parameters:
        - in: path
          name: account_id
          required: true
          type: string
          description: ID of the account
      produces:
        - application/json
      responses:
        "200":
          description: Account details retrieved successfully
          schema:
            $ref: "#/definitions/Account"
        "401":
          description: Unauthorized
        "404":
          description: Account not found
        "500":
          description: Internal Server Error

  /accounts/{account_id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transactions for an account
      description: Retrieve all transactions for the given account in the current month.
      parameters:
        - in: path
          name: account_id
          required: true
          type: string
          description: ID of the account
      produces:
        - application/json
      responses:
        "200":
          description: List of transactions for the account
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized
        "404":
          description: Account not found
        "500":
          description: Internal Server Error

  /accounts/{account_id}/transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction details
      description: Retrieve details of a specific transaction.
      parameters:
        - in: path
          name: account_id
          required: true
          type: string
          description: ID of the account
        - in: path
          name: transaction_id
          required: true
          type: string
          description: ID of the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction details
      description: Update user-specific details of a transaction (e.g., category, note).
      parameters:
        - in: path
          name: account_id
          required: true
          type: string
          description: ID of the account
        - in: path
          name: transaction_id
          required: true
          type: string
          description: ID of the transaction
        - in: body
          name: body
          description: Fields that can be updated (category, note)
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid request body
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  Account:
    type: object
    properties:
      id:
        type: string
        description: Account ID
      name:
        type: string
        description: Account name (e.g., "Checking Account")
      balance:
        type: number
        format: float
        description: Current account balance
      currency:
        type: string
        description: Currency of the account (e.g., "USD")

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      date:
        type: string
        format: date-time
        description: Date and time of the transaction
      amount:
        type: number
        format: float
        description: Transaction amount
      currency:
        type: string
        description: Currency of the transaction
      type:
        type: string
        description: Type of transaction (e.g., "Debit", "Credit")
      category:
        type: string
        description: User-defined category (e.g., "Groceries", "Rent")
      note:
        type: string
        description: Optional user-defined note
      recipient:
        type: string
        description: Recipient or merchant name

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Updated transaction category
      note:
        type: string
        description: Updated user note
